<a href="https://colab.research.google.com/github/aanchalsh/Machine-Learning/blob/main/Data_Preprocessing_ML_lab_1_11_10_data_csv_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np 
import pandas as pd

## Importing the dataset

In [ ]:
dataset=pd.read_csv('/Data.csv - Data.csv (1).csv')
X=dataset.iloc[:, :-1].values
Y=dataset.iloc[: ,-1].values

print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]



ENCODING THE CATEGORICAL DATA


ENCODING THE INDEPENDANT VARIABLE



In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(X)
print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(Y)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_test,Y_train=train_test_split(x,y,test_size=0.2,random_state=12)
print(X_train)

[[1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])
print(X_train)




[[1.0 0.0 0.0 1.5894346798964514 1.7139162176397245]
 [1.0 0.0 0.0 0.963227856626714 1.0041267569245058]
 [0.0 1.0 0.0 0.3370210333569767 0.17040580306853492]
 [1.0 0.0 0.0 -0.13263408409532626 0.49713428498506385]
 [0.0 0.0 1.0 0.02391762172210805 -0.11125668134226649]
 [0.0 1.0 0.0 -1.2284960248173664 -0.8210461420574853]
 [0.0 0.0 1.0 -1.6981511422696693 -1.4294371083848156]
 [0.0 0.0 1.0 0.14568005958011265 -1.023843130833262]]
